# Site settings
title: Julie Huguet
description: 'Software Engineer'
url: 'http://www.julie-huguet.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Julie Huguet'
  email: j.huguet9@gmail.com
  twitter_username: JHuguet87
  #facebook_username: joshgerdes
  github_username:  LittleCatBear
  linkedin_username:  jhuguet
  tumblr_username: ajourneytonewzealand


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
